<?php

namespace AppBundle\Repository;

/**
 * DetalleFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleFacturaRepository extends \Doctrine\ORM\EntityRepository
{
}
